//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	config "github.com/edgewize/edgeQ/pkg/config"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EdgeQosBrokerConfig) DeepCopyInto(out *EdgeQosBrokerConfig) {
	*out = *in
	out.Broker = in.Broker
	out.Schedule = in.Schedule
	out.Queue = in.Queue
	if in.ServiceGroups != nil {
		in, out := &in.ServiceGroups, &out.ServiceGroups
		*out = make([]config.ServiceGroup, len(*in))
		copy(*out, *in)
	}
	out.PromMetrics = in.PromMetrics
	out.BaseOptions = in.BaseOptions
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EdgeQosBrokerConfig.
func (in *EdgeQosBrokerConfig) DeepCopy() *EdgeQosBrokerConfig {
	if in == nil {
		return nil
	}
	out := new(EdgeQosBrokerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EdgeQosProxyConfig) DeepCopyInto(out *EdgeQosProxyConfig) {
	*out = *in
	out.Proxy = in.Proxy
	out.ServiceGroup = in.ServiceGroup
	out.BaseOptions = in.BaseOptions
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EdgeQosProxyConfig.
func (in *EdgeQosProxyConfig) DeepCopy() *EdgeQosProxyConfig {
	if in == nil {
		return nil
	}
	out := new(EdgeQosProxyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Hardware) DeepCopyInto(out *Hardware) {
	*out = *in
	if in.Models != nil {
		in, out := &in.Models, &out.Models
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Hardware.
func (in *Hardware) DeepCopy() *Hardware {
	if in == nil {
		return nil
	}
	out := new(Hardware)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageConfig) DeepCopyInto(out *ImageConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageConfig.
func (in *ImageConfig) DeepCopy() *ImageConfig {
	if in == nil {
		return nil
	}
	out := new(ImageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferModelDeployment) DeepCopyInto(out *InferModelDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferModelDeployment.
func (in *InferModelDeployment) DeepCopy() *InferModelDeployment {
	if in == nil {
		return nil
	}
	out := new(InferModelDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InferModelDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferModelDeploymentList) DeepCopyInto(out *InferModelDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InferModelDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferModelDeploymentList.
func (in *InferModelDeploymentList) DeepCopy() *InferModelDeploymentList {
	if in == nil {
		return nil
	}
	out := new(InferModelDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InferModelDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferModelDeploymentSpec) DeepCopyInto(out *InferModelDeploymentSpec) {
	*out = *in
	in.DeploymentTemplate.DeepCopyInto(&out.DeploymentTemplate)
	if in.NodeSelectors != nil {
		in, out := &in.NodeSelectors, &out.NodeSelectors
		*out = make([]ModelNodeSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferModelDeploymentSpec.
func (in *InferModelDeploymentSpec) DeepCopy() *InferModelDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(InferModelDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferModelDeploymentStatus) DeepCopyInto(out *InferModelDeploymentStatus) {
	*out = *in
	if in.WorkLoadInstances != nil {
		in, out := &in.WorkLoadInstances, &out.WorkLoadInstances
		*out = make(map[string]WorkLoadStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferModelDeploymentStatus.
func (in *InferModelDeploymentStatus) DeepCopy() *InferModelDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(InferModelDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferModelService) DeepCopyInto(out *InferModelService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferModelService.
func (in *InferModelService) DeepCopy() *InferModelService {
	if in == nil {
		return nil
	}
	out := new(InferModelService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InferModelService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferModelServiceList) DeepCopyInto(out *InferModelServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InferModelService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferModelServiceList.
func (in *InferModelServiceList) DeepCopy() *InferModelServiceList {
	if in == nil {
		return nil
	}
	out := new(InferModelServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InferModelServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferModelServiceSpec) DeepCopyInto(out *InferModelServiceSpec) {
	*out = *in
	in.BrokerConfig.DeepCopyInto(&out.BrokerConfig)
	out.ProxyConfig = in.ProxyConfig
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferModelServiceSpec.
func (in *InferModelServiceSpec) DeepCopy() *InferModelServiceSpec {
	if in == nil {
		return nil
	}
	out := new(InferModelServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferModelServiceStatus) DeepCopyInto(out *InferModelServiceStatus) {
	*out = *in
	if in.ServiceGroups != nil {
		in, out := &in.ServiceGroups, &out.ServiceGroups
		*out = make(map[string]ServiceGroupItem, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferModelServiceStatus.
func (in *InferModelServiceStatus) DeepCopy() *InferModelServiceStatus {
	if in == nil {
		return nil
	}
	out := new(InferModelServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferModelTemplate) DeepCopyInto(out *InferModelTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferModelTemplate.
func (in *InferModelTemplate) DeepCopy() *InferModelTemplate {
	if in == nil {
		return nil
	}
	out := new(InferModelTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InferModelTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferModelTemplateList) DeepCopyInto(out *InferModelTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InferModelTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferModelTemplateList.
func (in *InferModelTemplateList) DeepCopy() *InferModelTemplateList {
	if in == nil {
		return nil
	}
	out := new(InferModelTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InferModelTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferModelTemplateSpec) DeepCopyInto(out *InferModelTemplateSpec) {
	*out = *in
	if in.ServiceGroup != nil {
		in, out := &in.ServiceGroup, &out.ServiceGroup
		*out = make(map[string]int, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferModelTemplateSpec.
func (in *InferModelTemplateSpec) DeepCopy() *InferModelTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(InferModelTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferModelTemplateStatus) DeepCopyInto(out *InferModelTemplateStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferModelTemplateStatus.
func (in *InferModelTemplateStatus) DeepCopy() *InferModelTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(InferModelTemplateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferModelTemplateVersion) DeepCopyInto(out *InferModelTemplateVersion) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferModelTemplateVersion.
func (in *InferModelTemplateVersion) DeepCopy() *InferModelTemplateVersion {
	if in == nil {
		return nil
	}
	out := new(InferModelTemplateVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InferModelTemplateVersion) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferModelTemplateVersionList) DeepCopyInto(out *InferModelTemplateVersionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InferModelTemplateVersion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferModelTemplateVersionList.
func (in *InferModelTemplateVersionList) DeepCopy() *InferModelTemplateVersionList {
	if in == nil {
		return nil
	}
	out := new(InferModelTemplateVersionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InferModelTemplateVersionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferModelTemplateVersionSpec) DeepCopyInto(out *InferModelTemplateVersionSpec) {
	*out = *in
	if in.ServiceGroup != nil {
		in, out := &in.ServiceGroup, &out.ServiceGroup
		*out = make(map[string]int, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ModelServerSpec != nil {
		in, out := &in.ModelServerSpec, &out.ModelServerSpec
		*out = new(ModelServerSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.DeploymentSpec != nil {
		in, out := &in.DeploymentSpec, &out.DeploymentSpec
		*out = new(ModelDeploymentSpec)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferModelTemplateVersionSpec.
func (in *InferModelTemplateVersionSpec) DeepCopy() *InferModelTemplateVersionSpec {
	if in == nil {
		return nil
	}
	out := new(InferModelTemplateVersionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferModelTemplateVersionStatus) DeepCopyInto(out *InferModelTemplateVersionStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferModelTemplateVersionStatus.
func (in *InferModelTemplateVersionStatus) DeepCopy() *InferModelTemplateVersionStatus {
	if in == nil {
		return nil
	}
	out := new(InferModelTemplateVersionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InnerDeploymentTemplate) DeepCopyInto(out *InnerDeploymentTemplate) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InnerDeploymentTemplate.
func (in *InnerDeploymentTemplate) DeepCopy() *InnerDeploymentTemplate {
	if in == nil {
		return nil
	}
	out := new(InnerDeploymentTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MethodDetail) DeepCopyInto(out *MethodDetail) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MethodDetail.
func (in *MethodDetail) DeepCopy() *MethodDetail {
	if in == nil {
		return nil
	}
	out := new(MethodDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelDeploymentSpec) DeepCopyInto(out *ModelDeploymentSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.Template.DeepCopyInto(&out.Template)
	in.Strategy.DeepCopyInto(&out.Strategy)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelDeploymentSpec.
func (in *ModelDeploymentSpec) DeepCopy() *ModelDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(ModelDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelNodeSelector) DeepCopyInto(out *ModelNodeSelector) {
	*out = *in
	if in.ResourceRequest != nil {
		in, out := &in.ResourceRequest, &out.ResourceRequest
		*out = make(map[string]int, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelNodeSelector.
func (in *ModelNodeSelector) DeepCopy() *ModelNodeSelector {
	if in == nil {
		return nil
	}
	out := new(ModelNodeSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelServerSpec) DeepCopyInto(out *ModelServerSpec) {
	*out = *in
	if in.Servables != nil {
		in, out := &in.Servables, &out.Servables
		*out = make([]ServableConfigs, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Image = in.Image
	if in.HardwareSupport != nil {
		in, out := &in.HardwareSupport, &out.HardwareSupport
		*out = make([]Hardware, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelServerSpec.
func (in *ModelServerSpec) DeepCopy() *ModelServerSpec {
	if in == nil {
		return nil
	}
	out := new(ModelServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServableConfigs) DeepCopyInto(out *ServableConfigs) {
	*out = *in
	if in.Methods != nil {
		in, out := &in.Methods, &out.Methods
		*out = make([]MethodDetail, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServableConfigs.
func (in *ServableConfigs) DeepCopy() *ServableConfigs {
	if in == nil {
		return nil
	}
	out := new(ServableConfigs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceGroupItem) DeepCopyInto(out *ServiceGroupItem) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceGroupItem.
func (in *ServiceGroupItem) DeepCopy() *ServiceGroupItem {
	if in == nil {
		return nil
	}
	out := new(ServiceGroupItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkLoadStatus) DeepCopyInto(out *WorkLoadStatus) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkLoadStatus.
func (in *WorkLoadStatus) DeepCopy() *WorkLoadStatus {
	if in == nil {
		return nil
	}
	out := new(WorkLoadStatus)
	in.DeepCopyInto(out)
	return out
}
