kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edge-qos
  labels:
    {{- include "edge-qos-controller.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
    verbs:
      - create
      - get
      - delete
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - get
      - delete
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - get
      - delete
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - watch
      - list
  - resources:
      - deployments/status
    verbs:
      - get
      - update
      - patch
    apiGroups:
      - apps
  - apiGroups:
      - apps.edgewize.io
    resources:
      - infermodeldeployments
      - infermodelservices
      - infermodeltemplates
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps.edgewize.io
    resources:
      - infermodeldeployments/finalizers
      - infermodelservices/finalizers
    verbs:
      - update
  - apiGroups:
      - apps.edgewize.io
    resources:
      - infermodeldeployments/status
      - infermodelservices/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - apps.edgewize.io
    resources:
      - infermodeltemplateversions
    verbs:
      - delete
      - get
      - list
      - watch
