apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.webhook.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: edge-qos-controller-manager
    {{- include "edge-qos-controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.webhook.type }}
  ports:
    - port: {{ .Values.service.webhook.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app: edge-qos-controller-manager
    {{- include "edge-qos-controller.selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.apiserver.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: edge-qos-apiserver
    {{- include "edge-qos-controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.apiserver.type }}
  ports:
    - port: {{ .Values.service.apiserver.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: edge-qos-apiserver
    {{- include "edge-qos-controller.selectorLabels" . | nindent 4 }}

