# Default values for edge-qos-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

global:
  imageRegistry: "mirrors.thingsdao.com"
  imagePullPolicy: "IfNotPresent"
  imagePullSecrets:
    - name: edge-deploy-secret

imageReference:
  edgeQosApiserver:
    imageRegistry: ""
    name: "edgewize/edge-qos-apiserver"
    tag: "latest"
    imagePullSecrets: [ ]
  edgeQosController:
    imageRegistry: ""
    name: "edgewize/edge-qos-controller"
    tag: "latest"
    imagePullSecrets: []
  edgeQosProxy:
    imageRegistry: ""
    name: "edgewize/edge-qos-proxy"
    tag: "latest"
  edgeQosBroker:
    imageRegistry: ""
    name: "edgewize/edge-qos-broker"
    tag: "latest"
  initIptables:
    name: "edgewize/init-iptables"
    tag: "latest"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  webhook:
    name: edge-qos-webhook
    type: ClusterIP
    port: 8444
  apiserver:
    name: edge-qos-apiserver
    type: ClusterIP
    port: 9091

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
   limits:
     cpu: 500m
     memory: 512Mi
   requests:
     cpu: 100m
     memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/edge
              operator: DoesNotExist

edgeQosProxy:
  conf:
    base:
      profPathPrefix: debug
      logLevel: info
      profEnable: false
    proxy:
      addr: 0.0.0.0:15051
      dialTimeout: 30s
      keepAlive: 1m0s
      headerTimeout: 1m0s
      idleConnTimeout: 1m0s
      maxIdleConns: 1000
      MaxConnsPerHost: 1000
      readTimeout: 1m0s
      writeTimeout: 1m0s
    serviceGroup:
      name: pay

edgeQosBroker:
  conf:
    promMetrics:
      addr: 0.0.0.0:5501
      scrapeInterval: 1m
    base:
      profPathPrefix: debug
      logLevel: info
      profEnable: false
    broker:
      addr: 0.0.0.0:15050
      dialTimeout: 30s
      keepAlive: 1m0s
      headerTimeout: 1m0s
      idleConnTimeout: 1m0s
      maxIdleConns: 1000
      MaxConnsPerHost: 1000
      readTimeout: 1m0s
      writeTimeout: 1m0s
      workPoolSize: 5
    schedule:
      method: WRR
      enableFlowControl: true
    queue:
      size: 200
    serviceGroups:
      - name: default
        weight: 100
      - name: pay
        weight: 20
      - name: security
        weight: 400
