/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	appsv1alpha1 "github.com/edgewize/edgeQ/pkg/apis/apps/v1alpha1"
	scheme "github.com/edgewize/edgeQ/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// InferModelServicesGetter has a method to return a InferModelServiceInterface.
// A group's client should implement this interface.
type InferModelServicesGetter interface {
	InferModelServices(namespace string) InferModelServiceInterface
}

// InferModelServiceInterface has methods to work with InferModelService resources.
type InferModelServiceInterface interface {
	Create(ctx context.Context, inferModelService *appsv1alpha1.InferModelService, opts v1.CreateOptions) (*appsv1alpha1.InferModelService, error)
	Update(ctx context.Context, inferModelService *appsv1alpha1.InferModelService, opts v1.UpdateOptions) (*appsv1alpha1.InferModelService, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, inferModelService *appsv1alpha1.InferModelService, opts v1.UpdateOptions) (*appsv1alpha1.InferModelService, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*appsv1alpha1.InferModelService, error)
	List(ctx context.Context, opts v1.ListOptions) (*appsv1alpha1.InferModelServiceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *appsv1alpha1.InferModelService, err error)
	InferModelServiceExpansion
}

// inferModelServices implements InferModelServiceInterface
type inferModelServices struct {
	*gentype.ClientWithList[*appsv1alpha1.InferModelService, *appsv1alpha1.InferModelServiceList]
}

// newInferModelServices returns a InferModelServices
func newInferModelServices(c *AppsV1alpha1Client, namespace string) *inferModelServices {
	return &inferModelServices{
		gentype.NewClientWithList[*appsv1alpha1.InferModelService, *appsv1alpha1.InferModelServiceList](
			"infermodelservices",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *appsv1alpha1.InferModelService { return &appsv1alpha1.InferModelService{} },
			func() *appsv1alpha1.InferModelServiceList { return &appsv1alpha1.InferModelServiceList{} },
		),
	}
}
