/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/edgewize/edgeQ/pkg/apis/apps/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeInferModelServices implements InferModelServiceInterface
type FakeInferModelServices struct {
	Fake *FakeAppsV1alpha1
	ns   string
}

var infermodelservicesResource = v1alpha1.SchemeGroupVersion.WithResource("infermodelservices")

var infermodelservicesKind = v1alpha1.SchemeGroupVersion.WithKind("InferModelService")

// Get takes name of the inferModelService, and returns the corresponding inferModelService object, and an error if there is any.
func (c *FakeInferModelServices) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.InferModelService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(infermodelservicesResource, c.ns, name), &v1alpha1.InferModelService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.InferModelService), err
}

// List takes label and field selectors, and returns the list of InferModelServices that match those selectors.
func (c *FakeInferModelServices) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.InferModelServiceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(infermodelservicesResource, infermodelservicesKind, c.ns, opts), &v1alpha1.InferModelServiceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.InferModelServiceList{ListMeta: obj.(*v1alpha1.InferModelServiceList).ListMeta}
	for _, item := range obj.(*v1alpha1.InferModelServiceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested inferModelServices.
func (c *FakeInferModelServices) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(infermodelservicesResource, c.ns, opts))

}

// Create takes the representation of a inferModelService and creates it.  Returns the server's representation of the inferModelService, and an error, if there is any.
func (c *FakeInferModelServices) Create(ctx context.Context, inferModelService *v1alpha1.InferModelService, opts v1.CreateOptions) (result *v1alpha1.InferModelService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(infermodelservicesResource, c.ns, inferModelService), &v1alpha1.InferModelService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.InferModelService), err
}

// Update takes the representation of a inferModelService and updates it. Returns the server's representation of the inferModelService, and an error, if there is any.
func (c *FakeInferModelServices) Update(ctx context.Context, inferModelService *v1alpha1.InferModelService, opts v1.UpdateOptions) (result *v1alpha1.InferModelService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(infermodelservicesResource, c.ns, inferModelService), &v1alpha1.InferModelService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.InferModelService), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeInferModelServices) UpdateStatus(ctx context.Context, inferModelService *v1alpha1.InferModelService, opts v1.UpdateOptions) (*v1alpha1.InferModelService, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(infermodelservicesResource, "status", c.ns, inferModelService), &v1alpha1.InferModelService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.InferModelService), err
}

// Delete takes name of the inferModelService and deletes it. Returns an error if one occurs.
func (c *FakeInferModelServices) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(infermodelservicesResource, c.ns, name, opts), &v1alpha1.InferModelService{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeInferModelServices) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(infermodelservicesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.InferModelServiceList{})
	return err
}

// Patch applies the patch and returns the patched inferModelService.
func (c *FakeInferModelServices) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.InferModelService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(infermodelservicesResource, c.ns, name, pt, data, subresources...), &v1alpha1.InferModelService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.InferModelService), err
}
