# Build the manager binary
FROM --platform=$TARGETPLATFORM golang:1.21 as builder
ARG TARGETPLATFORM
ARG BUILDPLATFORM

WORKDIR /workspace
# Copy the Go Modules manifests
COPY . .
RUN go mod tidy
RUN CGO_ENABLED=0 go build -a -o model tests/mock/model/model.go

FROM --platform=$TARGETPLATFORM golang:1.21
ARG TARGETPLATFORM
ARG BUILDPLATFORM

WORKDIR /
COPY --from=builder /workspace/model .
USER 65532:65532

ENTRYPOINT ["/model"]