/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/edgewize/edgeQ/pkg/apis/apps/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// InferModelServiceLister helps list InferModelServices.
// All objects returned here must be treated as read-only.
type InferModelServiceLister interface {
	// List lists all InferModelServices in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.InferModelService, err error)
	// InferModelServices returns an object that can list and get InferModelServices.
	InferModelServices(namespace string) InferModelServiceNamespaceLister
	InferModelServiceListerExpansion
}

// inferModelServiceLister implements the InferModelServiceLister interface.
type inferModelServiceLister struct {
	indexer cache.Indexer
}

// NewInferModelServiceLister returns a new InferModelServiceLister.
func NewInferModelServiceLister(indexer cache.Indexer) InferModelServiceLister {
	return &inferModelServiceLister{indexer: indexer}
}

// List lists all InferModelServices in the indexer.
func (s *inferModelServiceLister) List(selector labels.Selector) (ret []*v1alpha1.InferModelService, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.InferModelService))
	})
	return ret, err
}

// InferModelServices returns an object that can list and get InferModelServices.
func (s *inferModelServiceLister) InferModelServices(namespace string) InferModelServiceNamespaceLister {
	return inferModelServiceNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// InferModelServiceNamespaceLister helps list and get InferModelServices.
// All objects returned here must be treated as read-only.
type InferModelServiceNamespaceLister interface {
	// List lists all InferModelServices in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.InferModelService, err error)
	// Get retrieves the InferModelService from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.InferModelService, error)
	InferModelServiceNamespaceListerExpansion
}

// inferModelServiceNamespaceLister implements the InferModelServiceNamespaceLister
// interface.
type inferModelServiceNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all InferModelServices in the indexer for a given namespace.
func (s inferModelServiceNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.InferModelService, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.InferModelService))
	})
	return ret, err
}

// Get retrieves the InferModelService from the indexer for a given namespace and name.
func (s inferModelServiceNamespaceLister) Get(name string) (*v1alpha1.InferModelService, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("infermodelservice"), name)
	}
	return obj.(*v1alpha1.InferModelService), nil
}
