apiVersion: v1
kind: Service
metadata:
  name: {{ include "edge-qos-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edge-qos-controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "edge-qos-controller.selectorLabels" . | nindent 4 }}
